import './globals.css'

export const revalidate = 0;

export const metadata = {
  title: 'Dr. Seeto ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='flex flex-col 2xl:items-center w-full'>
          <div className='max-w-screen-2xl w-full bg-white'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
